// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTp3FPEP1Nhn0E_5KIal97dl557Dm4GQk',
    appId: '1:444854952778:android:63c03c001adb5c6de197b3',
    messagingSenderId: '444854952778',
    projectId: 'todo-firebase-provider-9687',
    databaseURL: 'https://todo-firebase-provider-9687-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-firebase-provider-9687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbGhsaxttbMx-54ucLNXwp6K6Q1pnpT1E',
    appId: '1:444854952778:ios:00e35040e7edb7cee197b3',
    messagingSenderId: '444854952778',
    projectId: 'todo-firebase-provider-9687',
    databaseURL: 'https://todo-firebase-provider-9687-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-firebase-provider-9687.appspot.com',
    androidClientId: '444854952778-7cq6f23s41o39g0affrft437fqrmkrq1.apps.googleusercontent.com',
    iosClientId: '444854952778-h6hg8ik3q5pqunrmv5jpve3fbaeunf4n.apps.googleusercontent.com',
    iosBundleId: 'com.anirudhmpai.providerFirebaseTodo',
  );
}
